### ISSUE TITLE
Possibility to maintain this repository

### ISSUE THREAD

**Issue by omnilight** [mcustiel/codeception-wiremock-extension#3]
Hi, @mcustiel 

Here at Lamoda (Russian eCom Company, lamoda.ru) we have found this project awesome and using it to interact with wiremock in our php tests.

Still, as we can see this extension is not mantain anymore, so we had to fork it here https://github.com/lamoda/codeception-wiremock-extension to be able to support it.

But is it possible for you to grant permissions for us to be a maintainers of this extension here?

**Comment by mcustiel** [comment]
Added @omnilight  as colaborator
